### ISSUE TITLE
Add CI tests against multiple dbt projects (jaffle_shop, `dbt init` project)

### ISSUE THREAD

**Issue by tjwaterman99** [tjwaterman99/artefacts#17]
I think we can add at least the dbt init starter project and the jaffle shop projects

**Comment by tjwaterman99** [comment]
I think the CI suite ran with `pytest` can include all dbt projects, so it's not necessary to include this parameter in the matric of CI suites. The matrix should just be python versions and dbt versions.

```yml
strategy:
  matrix:
    dbt_version: [0.21.0, 0.22.rc0]
    python_version: [3.6, 3.7, 3.8, 3.9]
```
